### ISSUE TITLE
bamboohr/api doesn't exist in packagist

### ISSUE THREAD

**Issue by gregholland** [BambooHR/bhr-api-php#12]
https://packagist.org/packages/bamboohr/

**Comment by tylercd100** [comment]
+1 this will make it easier to manage with composer, please add to packagist :)
`composer require bamboohr/api`

**Comment by ciaranmcnulty** [comment]
+1 also a license would be good

**Comment by ncareau** [comment]
It is now in packagist.org at https://packagist.org/packages/bamboohr/api
This ticket can be closed. As for the LICENSE, there is a file but empty, we should open a new Issue.
